### ISSUE TITLE
not loading the coupon code 

### ISSUE THREAD

**Issue by jaygangurde** [gatsbyjs/store.gatsbyjs.org#484]

**Comment by jaygangurde** [comment]
Cannot read property 'trim' of null
TypeError: Cannot read property 'trim' of null
    at Object.exports.emptybody (/app/peril-downloaded-gatsbyjs/gatsby@peril/rules/emptybody.ts:12:14)
    at Object.exports.default (/app/peril-downloaded-gatsbyjs/gatsby@peril/rules/emptybody.ts:17:13)
    at Object.<anonymous> (/app/node_modules/danger/distribution/runner/runners/inline.js:147:60)
    at step (/app/node_modules/danger/distribution/runner/runners/inline.js:32:23)
    at Object.next (/app/node_modules/danger/distribution/runner/runners/inline.js:13:53)
    at /app/node_modules/danger/distribution/runner/runners/inline.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/danger/distribution/runner/runners/inline.js:3:12)
    at Object.exports.runDangerfileEnvironment (/app/node_modules/danger/distribution/runner/runners/inline.js:105:136)
    at runDangerAgainstFileInline (/app/out/danger/danger_runner.js:56:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
